### ISSUE TITLE
Can you add a simple GUI Interface??

### ISSUE THREAD

**Issue by Marcuswright1** [machinateur/android-chrome-tab-transfer#31] opened 2024-09-07 15:46 UTC
@machinateur 
First of all what a amazing tool (or script whatever its called). Thanks a lot to your time & effort in developing this tool.

Iam not a tech savvy guy. But understand a few things here and there. After finding for ages to backup my 1000+ tabs in Chrome, I came across a post someone had written on a reddit article on this which got me to your repository.

After taking help from my friend to understand what all these things are and how to get all these working. I finally backed up all my 1000+ Chrome tabs on my older phone. Although it seems to be hard to understand at first, later it turned out to be easy.

The main point is can you create a simple GUI Interface for easier use of the tool, it would be of a great help. To us non tech savvy guys.

Thanks alot for your contribution once again 😀

**Comment by machinateur** [comment] 2024-10-26 17:46
Hello @Marcuswright1,

thank's for the feedback and kind words! I'm glad you were able to make the tool work for your benefit.

I've thought about ways to craft a graphical user interface for this, but in it's current form (i.e. based on PHP, as server-side programming language) is not sufficient to support proper GUI.

I've now started looking into this a bit more. I might come up with a solution. But given my plans to introduce iOS support as well as some other structural changes to the software, this might take a while.

**Comment by machinateur** [comment] 2024-10-26 23:54
Closing here, as duplicate of #27.

**Closed as completed by machinateur** 2024-10-26 23:54 UTC
Labels: duplicate
